version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
clone_folder: C:\projects\Project3\Game\
build:
  project: Engine.sln
  verbosity: normal
artifacts:
- path: Game
  name: Project3
deploy:
- provider: GitHub
  auth_token:
    secure: QhydgyQMxm8l8l9gAV7ByY9TCaj7XY0plvUrout15RVMfURdWPupt/Ra560eLxeO
  draft: false
  force_update: true