#ifndef __AUDIOEVENT_H__
#define __AUDIOEVENT_H__

#include "Wwise_Library.h"
#include <string>

class SoundBank;

class AudioEvent
{
public:

	AudioEvent();							// Constructor that associates the callback

	bool IsEventPlaying() const;			// Is the Event Playing?
	void Unload();							// Set to Unload
	void Unloaded();						// Once unloaded
	bool IsReadyToUnload() const;			// Check if it ready to be unloaded

	std::string name;						// Name of the event
	unsigned int id = 0;					// ID event generated by Wwise

	bool sound_3D = false;					// Is this sound 3D positioning?
	float max_attenuation = 0.0f;			// Max unit of attenuation

	AkPlayingID playing_id = 0L;						// When Event is played, is different from 0L
	AkCallbackFunc event_call_back = nullptr;			// Call back function

	SoundBank *parent_soundbank = nullptr;			// Path for Soundbank's Event

private:

	bool unload = false;

};

#endif